# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Richard M. Pasco
title: Information Technology Consultant
email: mail@rmpas.co
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Richard and I'm an I.T. Consultant. I have ~15 years of experience in Software Development for research, specializing in ICT4Ag. I have a passion for learning and applying emerging ICT technologies for problem-solving in different fields. I am always looking for new challenges and opportunities to grow my skill set.
  
  Currently, I specialize in: <mark>Software Project Management</mark>, <mark>System Administration</mark>, <mark>Web Technologies</mark>, and <mark>Software Backend Development</mark>.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: University of the Philippines Los Baños
        caption: 2013 - 2015
        sub_title: Master of Information Technology

      - layout: top-middle
        title: University of the Philippines Los Baños
        caption: 2006 - 2011
        sub_title: BSc Computer Science

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
  - title: Skillset # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Software Development
        description: | # this will include new lines to allow paragraphs
          * Languages: C/++, Java, Javascript, Python, PHP, Pascal
          * Platforms: Windows, Linux (Debian, Ubuntu, Raspbian), Android
          * Frameworks: Cordova, NodeJS, Wordpress
          * Databases: MySQL, SQLite, PostgreSQL
          * Tools: Git, Docker, Proxmox, Copilot
          * Others: RESTful APIs, websockets, MQTT, OAuth

      - layout: left
        border: weak
        title: System Administration
        description: | # this will include new lines to allow paragraphs
          * OS: Linux (Debian, Ubuntu, Raspbian)
          * Hypervisors and Containers: Proxmox, Docker, LXCs, VMs
          * Monitoring: Prometheus, Grafana, MQTT, HTTP
          * Automation: Ansible, Bash, Python

      - layout: left
        border: weak
        title: Project Management
        description: | # this will include new lines to allow paragraphs
          * Product Development: Conceptualization, Design, Implementation, Pilot, Deployment
          * Technology survey and selection
          * Project Planning: Gantt, Agile, Kanban
          * Resource Management: AWS, Project Teams, Coordination, Budgets
          * Documentation: Technical, User, Training
          * Communication: Stakeholder, Team, Client

      - layout: left
        title: Others
        description: | # this will include new lines to allow paragraphs
          * Hardware: Setup and troubleshooting of SoCs (Raspberry Pi, ESP32), Rackmount Servers, Sensors and IoT devices
          * Networking: LAN, DNS, Proxies
          * Security: Firewalls, VPNs, Encryption
          * DevOps: CI/CD, Monitoring, Automation

  - title: Work Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: BioInformatics HPC (System Administrator, 2025)
        quote: >
          Configuration of a high-performance computing (HPC) cluster for bioinformatics research.
        description: | # this will include new lines to allow paragraphs
          This project involved the movement of physical units from one location to another, and the reconfiguration of the units to form a high-performance computing (HPC) cluster. The initial plan is to reset all the existing servers and reconfigure them into a purely <mark>virtualized computing environment</mark> using <mark>Proxmox</mark> as the hypervisor to provide computing resources to clients.
          
      - layout: top-middle
        title: EasyFarm (Product Manager, 2024)
        quote: >
          Evolution of EasyHarvest, a platform for farmers to connect with resource suppliers.
        description: | # this will include new lines to allow paragraphs
          EasyFarm is an evolution of EasyHarvest, which was developed in 2017. The platform is a <mark>Cross-platform mobile application</mark> that was developed using <mark>React Native</mark> for the app, and <mark>Wordpress</mark> for the backend. It made use of many third-party APIs and Wordpress plugins to significantly add more scope and features to the former application, such as the introduction of a marketplace for agricultural inputs.

      - layout: top-middle
        title: e-Extension for Agriculture (Product Manager, 2023-2024)
        quote: >
          Pioneering agricultural extension services linked with social media and artificial intelligence.
        description: | # this will include new lines to allow paragraphs
          Conceptualized and co-developed an e-Extension platform for the dissemination of agricultural information to farmers in Laos and Vietnam. Aside from the traditional e-Extension services delivered via simple resource-hosting websites, the platform also integrated <mark>social media APIs</mark> and <mark>LLM</mark> for the delivery of more personalized and timely information to farmers that is both highly available and accessible.

      - layout: top-middle
        title: Source-selective and Emission-adjusted GHG Calculator for Cropland (SECTOR) (Developer, 2019)
        quote: >
          Progenitor for a number of GHG calculators for different land uses currently in use in Thailand.
        description: | # this will include new lines to allow paragraphs
          The initial version of SECTOR was developed using <mark>MS Excel</mark> and the <mark>Visual Basic for Applications (VBA)</mark> for the macro-based backend. It relied on the templating of scenarios and calculations to provide a context-scalable and user-friendly interface for the calculation of GHG emissions from cropland.

      - layout: top-middle
        title: EasyHarvest (Developer, 2017)
        quote: >
          An exploration of an Uber-like platform for farmers to connect with combine harvester owners.
        description: | # this will include new lines to allow paragraphs
          This is a <mark>progressive web application (PWA)</mark> that was developed using <mark>NodeJS</mark> for the backend, and <mark>HTML</mark>, <mark>CSS</mark>, and <mark>JavaScript</mark> for the frontend. <mark>CordovaJS</mark> mobile application framework was used to convert the web application into a mobile application.
        
      - layout: top-middle
        title: SALTS - Salinity Monitoring as a Timely Service (Developer, 2015)
        quote: >
          Monitoring of salinity levels in the Mekong Delta using hyper-localized data with GPS and IVR technology.
        description: | # this will include new lines to allow paragraphs
          Developed a web application for the monitoring of salinity levels in the Mekong Delta using hyper-localized data with GPS and IVR technology. The application was developed using <mark>NodeJS</mark> for the backend, and <mark>HTML</mark>, <mark>CSS</mark>, and <mark>JavaScript</mark> for the frontend. The application made use of <mark>Google APIs</mark> for the visualization of the data, <mark>IVR/SMS APIs</mark>, and a <mark>Linux Server</mark> deployed on AWS.

      - layout: top-middle
        title: Crop Modeling Systems - SAMARA, RIDEV (Developer, 2012)
        quote: >
          Development of crop modeling systems for agricultural research.
        description: | # this will include new lines to allow paragraphs
          Provided improvements to crop growth modeling backends to 2 crop modeling platforms developed with <mark>C</mark> and <mark>Pascal</mark> for the French Agricultural Research Centre for International Development (CIRAD).
          Acted as a resource person for workshops on the usage of the above platforms, and provided technical support for PhD students and other users from the crop modeling community.
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting

  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Internet-of-Things (IoT) Crash Course Workshop Sessions
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
        quote: >
          The goal is to enable students to do the software and hardware integration for IoT projects by themselves without relying on external contractors.
        description: | # this will include new lines to allow paragraphs
          From time to time, I lead workshops on IoT for beginners, mostly college-level Engineering students. The workshop is meant to teach fundamental concepts in IoT implementation, and for me to learn up-to-date skills, depending on what is widely used as standard. 
          
          We started with <mark>Arduino/NodeMCU</mark> devices with basic HTTP communication, the plan for the latest one (whenever that may be) is to use <mark>MQTT</mark> for the transmission, <mark>Prometheus</mark> for observability, and modern <mark>ESP32</mark> boards.
      
      - layout: top-middle
        title: Internet-of-Things (IoT) Student Projects
        additional_links:
        quote: >
          Once in a while, some students come along with an interesting project proposal, and I help them with the software and hardware integration.
        description: | # this will include new lines to allow paragraphs
          I have taken on just a few select student projects that I found interesting, the latest one was a project that involved creating a device that monitored for structural integrity with high-sensitivity vibration <mark>sensors</mark> and transmitted data via <mark>LoRa</mark>.

          For the software side, the platform is set up as a hub-node infrastructure, with the hub being a <mark>Raspberry Pi 4B</mark> and the nodes being the <mark>ESP32</mark> boards. Everything is observable via an online <mark>Grafana</mark> dashboard that is also configured to send alerts to specific email addresses.

      - layout: top-middle
        title: Home Laboratory
        additional_links:
        quote: >
          Small home setup for testing and learning new technologies.
        description: | # this will include new lines to allow paragraphs
          The goal of my homelab is to be able to have a testbed for trying out new technologies without paying for subscriptions. I have a few server devices in this setup that I have upgraded through the years: multiple Raspberry Pis (1,3B,4B), some Dell USFF PCs, and a few n100 miniPCs.

          So far, I have been able to learn and practice <mark>Authentication Technologies (oAuth, LDAP)</mark>, <mark>Containerization (Docker, Kubernetes)</mark>, <mark>Monitoring (Prometheus, Grafana)</mark>, and <mark>Automation (Ansible)</mark>. The OS of choice has evolved from Raspbian, to Ubuntu, and finally to Debian with <mark>Proxmox</mark> as the hypervisor for creating <mark>VMs</mark> and <mark>LXCs</mark>.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
