# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Richard M. Pasco
title: Information Technology Consultant
email: mail@rmpas.co
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Richard and I'm an I.T. Consultant. I have ~15 years of experience in <mark>Software Development</mark> for research, specializing in <mark>ICT4Ag</mark>. I have a passion for learning and applying emerging ICT technologies for problem-solving in different fields. I am always looking for new challenges and opportunities to grow my skill set.
  
  Currently, I specialize in: <mark>Software Project Management</mark>, <mark>System Administration</mark>, and <mark>Software Backend Development</mark>.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of the Philippines Los Baños
        caption: 2006 - 2011
        sub_title: BSc Computer Science
        quote: >
          The University of the Philippines Los Baños (UPLB), a coeducational publicly funded academic, research and extension institution, is one of the eight constituent universities of the University of the Philippines System, the country's top educational institution.
        # description: | # this will include new lines to allow paragraphs
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of the Philippines Los Baños
        caption: 2013 - 2015
        sub_title: Master of Information Technology
        quote: >
          The UPLB Graduate School administers residential and off-campus graduate programs of UPLB that are supervised by about 700 graduate faculty members from nine colleges and one school.
        # description: | # this will include new lines to allow paragraphs

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Internet-of-Things (IoT) Crash Course Workshop Sessions
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
        quote: >
          The goal is to enable students to do the software and hardware integration for IoT projects by themselves without relying on external contractors.
        description: | # this will include new lines to allow paragraphs
          From time to time, I lead workshops on IoT for beginners, mostly college-level Engineering students. The workshop is meant to teach fundamental concepts in IoT implementation, and for me to learn up-to-date skills, depending on what is widely used as standard. 
          
          We started with <mark>Arduino/NodeMCU</mark> devices with basic HTTP communication, the plan for the latest one (whenever that may be) is to use <mark>MQTT</mark> for the transmission, <mark>Prometheus</mark> for observability, and modern <mark>ESP32</mark> boards.
      
      - layout: top-middle
        title: Internet-of-Things (IoT) Projects
        additional_links:
        quote: >
          Once in a while, some students come along with an interesting project proposal, and I help them with the software and hardware integration.
        description: | # this will include new lines to allow paragraphs
          I have taken on just a few select student projects that I found interesting, the latest one was a project that involved creating a device that monitored for structural integrity with high-sensitivity vibration <mark>sensors</mark> and transmitted data via <mark>LoRa</mark>.

          For the software side, the platform is set up as a hub-node infrastructure, with the hub being a <mark>Raspberry Pi 4B</mark> and the nodes being the <mark>ESP32</mark> boards. Everything is observable via an online <mark>Grafana</mark> dashboard that is also configured to send alerts to specific email addresses.

  - title: Work Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
